spring:
  application:
    name: gateway-master
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试
        - id: route_ucenter
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://ucenter
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            # 转发地址格式为 uri/archive
            - Path=/ucenter/**
          filters:
            - name: AuthCheckFilter     #会话验证
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 20
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 20

        - id: route_product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - name: AuthCheckFilter     #会话验证
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 20
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 20

        - id: route_order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - name: AuthCheckFilter     #会话验证
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 20
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 20

        - id: route_wallet
          uri: lb://wallet
          predicates:
            - Path=/wallet/**
          filters:
            - name: AuthCheckFilter     #会话验证
            # redis限流 ， filter名称必须是RequestRateLimiter
            - name: RequestRateLimiter
              args:
                # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
                key-resolver: '#{@remoteAddrKeyResolver}'
                # 每秒最大访问次数
                redis-rate-limiter.replenishRate: 20
                # 令牌桶最大容量
                redis-rate-limiter.burstCapacity: 20

logging:
  level:
    # log 级别
    org.springframework.cloud.gateway: debug